const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const G5Board = sequelize.define('G5Board', {
    bo_table: {
      type: DataTypes.STRING(20),
      allowNull: false,
      defaultValue: '',
      primaryKey: true,
    },
    gr_id: {
      type: DataTypes.STRING(255),
      allowNull: false,
      defaultValue: '',
    },
    bo_subject: {
      type: DataTypes.STRING(255),
      allowNull: false,
      defaultValue: '',
    },
    bo_mobile_subject: {
      type: DataTypes.STRING(255),
      allowNull: false,
      defaultValue: '',
    },
    bo_device: {
      type: DataTypes.ENUM('both', 'pc', 'mobile'),
      allowNull: false,
      defaultValue: 'both',
    },
    bo_admin: {
      type: DataTypes.STRING(255),
      allowNull: false,
      defaultValue: '',
    },
    bo_list_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_read_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_write_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_reply_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_comment_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_upload_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_download_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_html_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_link_level: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_count_delete: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_count_modify: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_read_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_write_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_comment_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_download_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_use_category: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_category_list: { type: DataTypes.TEXT, allowNull: false },
    bo_use_sideview: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_file_content: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_secret: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_dhtml_editor: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_select_editor: { type: DataTypes.STRING(50), allowNull: false, defaultValue: '' },
    bo_use_rss_view: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_good: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_nogood: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_name: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_signature: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_ip_view: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_list_view: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_list_file: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_list_content: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_table_width: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_subject_len: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_mobile_subject_len: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_page_rows: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_mobile_page_rows: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_new: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_hot: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_image_width: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_skin: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_mobile_skin: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_include_head: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_include_tail: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_content_head: { type: DataTypes.TEXT, allowNull: false },
    bo_mobile_content_head: { type: DataTypes.TEXT, allowNull: false },
    bo_content_tail: { type: DataTypes.TEXT, allowNull: false },
    bo_mobile_content_tail: { type: DataTypes.TEXT, allowNull: false },
    bo_insert_content: { type: DataTypes.TEXT, allowNull: false },
    bo_gallery_cols: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_gallery_width: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_gallery_height: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_mobile_gallery_width: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_mobile_gallery_height: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_upload_size: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_reply_order: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_search: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_order: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_count_write: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_count_comment: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_write_min: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_write_max: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_comment_min: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_comment_max: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    bo_notice: { type: DataTypes.TEXT, allowNull: false },
    bo_upload_count: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_email: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_cert: { type: DataTypes.ENUM('', 'cert', 'adult', 'hp-cert', 'hp-adult'), allowNull: false, defaultValue: '' },
    bo_use_sns: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_use_captcha: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    bo_sort_field: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_1_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_2_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_3_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_4_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_5_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_6_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_7_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_8_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_9_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_10_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_1: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_2: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_4: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_5: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_6: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_7: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_8: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_9: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    bo_10: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
  }, {
    tableName: 'g5_board',
    timestamps: false,
    underscored: true,
  });

  G5Board.associate = (models) => {
    if (models.G5Group) { // Check if G5Group model is available
      G5Board.belongsTo(models.G5Group, { foreignKey: 'gr_id', targetKey: 'gr_id' });
    }
    // Define other associations here if needed
    // For example, a board has many posts (G5Write_dynamic_table)
    // This is more complex due to dynamic table names.
    // One approach is to have a method on G5Board to get its "Write" model dynamically.
  };

  return G5Board;
};
