const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const G5ShopItem = sequelize.define('G5ShopItem', {
    it_id: {
      type: DataTypes.STRING(20),
      allowNull: false,
      defaultValue: '',
      primaryKey: true,
    },
    ca_id: { type: DataTypes.STRING(10), allowNull: false, defaultValue: '0' },
    ca_id2: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    ca_id3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_skin: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_mobile_skin: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_name: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_seo_title: { type: DataTypes.STRING(200), allowNull: false, defaultValue: '' },
    it_maker: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_origin: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_brand: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_model: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_option_subject: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_supply_subject: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_type1: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_type2: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_type3: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_type4: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_type5: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_basic: { type: DataTypes.TEXT, allowNull: false },
    it_explan: { type: DataTypes.MEDIUMTEXT, allowNull: false },
    it_explan2: { type: DataTypes.MEDIUMTEXT, allowNull: false },
    it_mobile_explan: { type: DataTypes.MEDIUMTEXT, allowNull: false },
    it_cust_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_point_type: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_supply_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_notax: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_sell_email: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_use: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_nocoupon: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_soldout: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_stock_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_stock_sms: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_noti_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_sc_type: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_sc_method: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_sc_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_sc_minimum: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_sc_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_buy_min_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_buy_max_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_head_html: { type: DataTypes.TEXT, allowNull: false },
    it_tail_html: { type: DataTypes.TEXT, allowNull: false },
    it_mobile_head_html: { type: DataTypes.TEXT, allowNull: false },
    it_mobile_tail_html: { type: DataTypes.TEXT, allowNull: false },
    it_hit: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_time: { type: DataTypes.DATE, allowNull: false, defaultValue: '0000-00-00 00:00:00' },
    it_update_time: { type: DataTypes.DATE, allowNull: false, defaultValue: '0000-00-00 00:00:00' },
    it_ip: { type: DataTypes.STRING(25), allowNull: false, defaultValue: '' },
    it_order: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_tel_inq: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    it_info_gubun: { type: DataTypes.STRING(50), allowNull: false, defaultValue: '' },
    it_info_value: { type: DataTypes.TEXT, allowNull: false },
    it_sum_qty: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_use_cnt: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    it_use_avg: { type: DataTypes.DECIMAL(2,1), allowNull: false },
    it_shop_memo: { type: DataTypes.TEXT, allowNull: false },
    ec_mall_pid: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img1: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img2: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img4: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img5: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img6: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img7: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img8: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img9: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_img10: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_1_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_2_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_3_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_4_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_5_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_6_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_7_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_8_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_9_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_10_subj: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_1: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_2: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_4: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_5: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_6: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_7: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_8: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_9: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    it_10: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
  }, {
    tableName: 'g5_shop_item',
    timestamps: false,
    underscored: true,
  });

  return G5ShopItem;
};
