const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const G5ShopOrder = sequelize.define('G5ShopOrder', {
    od_id: {
      type: DataTypes.BIGINT.UNSIGNED,
      allowNull: false,
      primaryKey: true,
    },
    mb_id: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_name: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_email: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_tel: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_hp: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_zip1: { type: DataTypes.CHAR(3), allowNull: false, defaultValue: '' },
    od_zip2: { type: DataTypes.CHAR(3), allowNull: false, defaultValue: '' },
    od_addr1: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_addr2: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_addr3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_addr_jibeon: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_deposit_name: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_b_name: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_b_tel: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_b_hp: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_b_zip1: { type: DataTypes.CHAR(3), allowNull: false, defaultValue: '' },
    od_b_zip2: { type: DataTypes.CHAR(3), allowNull: false, defaultValue: '' },
    od_b_addr1: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_b_addr2: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_b_addr3: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_b_addr_jibeon: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_memo: { type: DataTypes.TEXT, allowNull: false },
    od_cart_count: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_cart_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_cart_coupon: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_send_cost: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_send_cost2: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_send_coupon: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_receipt_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_cancel_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_receipt_point: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_refund_price: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_bank_account: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_receipt_time: { type: DataTypes.DATE, allowNull: false, defaultValue: '0000-00-00 00:00:00' },
    od_coupon: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_misu: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_shop_memo: { type: DataTypes.TEXT, allowNull: false },
    od_mod_history: { type: DataTypes.TEXT, allowNull: false },
    od_status: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_hope_date: { type: DataTypes.DATEONLY, allowNull: false, defaultValue: '0000-00-00' },
    od_settle_case: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_other_pay_type: { type: DataTypes.STRING(100), allowNull: false, defaultValue: '' },
    od_test: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    od_mobile: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    od_pg: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_tno: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_app_no: { type: DataTypes.STRING(20), allowNull: false, defaultValue: '' },
    od_escrow: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    od_casseqno: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_tax_flag: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
    od_tax_mny: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_vat_mny: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_free_mny: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    od_delivery_company: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '0' },
    od_invoice: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_invoice_time: { type: DataTypes.DATE, allowNull: false, defaultValue: '0000-00-00 00:00:00' },
    od_cash: { type: DataTypes.TINYINT, allowNull: false },
    od_cash_no: { type: DataTypes.STRING(255), allowNull: false },
    od_cash_info: { type: DataTypes.TEXT, allowNull: false },
    od_time: { type: DataTypes.DATE, allowNull: false, defaultValue: '0000-00-00 00:00:00' },
    od_pwd: { type: DataTypes.STRING(255), allowNull: false, defaultValue: '' },
    od_ip: { type: DataTypes.STRING(25), allowNull: false, defaultValue: '' },
  }, {
    tableName: 'g5_shop_order',
    timestamps: false,
    underscored: true,
  });

  return G5ShopOrder;
};
